### ISSUE TITLE
How to launch

### ISSUE THREAD

**Issue by iaraUM** [CXgamer/MCsim#2]
Hi, i need an specific program for launch ?
how to launch ?
I have the next programs
*Net Beams
*Intellij Idea
*Java 8
*Minecraft with "Team extreme" launcher (MC version 1.7.10 + )
*jdk1.8.0_111

Help me plis

**Comment by Breina** [comment]
Hey man, thanks for showing interest in my old project. You will need the default Minecraft launcher that was active with the 1.8 version. To run it, you first need to download [the latest release](https://github.com/CXgamer/MC-ticker/releases/download/v0.3-pre-alpha/MC.ticker.0.0.3.zip). Inside, you will find a .jar file. Navigate to it using your favorite command-line program such as Command Prompt or Terminal and enter the command `java -jar MCticker.jar`, this will run the application.

Oh and the programs such as Net Beans, IntelliJ IDEA and JDK are required for developers, but if you just want to use the program these aren't used.

**Comment by iaraUM** [comment]
thanks, I think this will be the last problem. It shows me this error:
"E Could not initlialize the Simulator:
Invocation failed with error: java.lang.NoSuchMethodError:
   org.apache.commons.lang3.Validate.inclusiveBetween(JJJLjava/lang/String;)V"
u can help me ? :smiley: .

**Comment by iaraUM** [comment]
Solved, and installed minecraft 1.8 from the beginning :dancer: 
An screenshot https://imgur.com/a/PC66i58
Thanks

**Comment by Breina** [comment]
It's awesome seeming it working again! Thanks for your persistence. :D

Yeah the problem you described is when the Minecraft's libraries are overwritten by newer versions. Installing the old one would indeed fix the problem. :D
